### ISSUE TITLE
apk build fails on CI

### ISSUE THREAD

**Issue by sandreae** [p2panda/meli#148]
https://github.com/p2panda/meli/actions/runs/9424418728/job/25964589024

```bash
Preparing "Install Android SDK Build-Tools 30.0.3 (revision: 30.0.3)".
"Install Android SDK Build-Tools 30.0.3 (revision: 30.0.3)" ready.
Installing Android SDK Build-Tools 30.0.3 in /usr/local/lib/android/sdk/build-tools/30.0.3
"Install Android SDK Build-Tools 30.0.3 (revision: 30.0.3)" complete.
"Install Android SDK Build-Tools 30.0.3 (revision: 30.0.3)" finished.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':device_info_plus:compileReleaseJavaWithJavac'.
> error: invalid source release: 17

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 29s
Running Gradle task 'assembleNormalRelease'...                    1[50](https://github.com/p2panda/meli/actions/runs/9424418728/job/25964589024#step:10:51).2s
Gradle task assembleNormalRelease failed with exit code 1
Error: Process completed with exit code 1.
```

**Comment by achou11** [comment]
for posterity, looks like a solution is to upgrade Java to 17

https://stackoverflow.com/a/78314958

**Comment by achou11** [comment]
> > for posterity, looks like a solution is to upgrade Java to 17
> > 
> > https://stackoverflow.com/a/78314958
> 
> Tried that out here https://github.com/p2panda/meli/pull/149 and still seeing the same error.
> 
> https://github.com/p2panda/meli/actions/runs/9498045895
> 

probably need to update this line in the workflow as well:

https://github.com/p2panda/meli/blob/e19b8a45a70a63ce1c42620a16a62d133e6e68bc/.github/workflows/build-android.yml#L31

**Comment by sandreae** [comment]
yay: https://github.com/p2panda/meli/actions/runs/9500022166/job/26182150228
