### ISSUE TITLE
Auto-fill suggestion chosen when value is empty string

### ISSUE THREAD

**Issue by sandreae** [p2panda/meli#39]
Noticed this on the sightings screen "local name" input. To reproduce:

- click edit button, leave value empty, click "enter" on the keyboard
- repeat
- at some point an auto-fill value is chosen instead of empty string

**Comment by sandreae** [comment]
Noticed this when working on the "used for" widget as well 🤔 (which reuses auto-fill functionality too) couldn't track down the source as well.

**Comment by adzialocha** [comment]
Maybe it has something to do with delayed state through the debounced function
