### ISSUE TITLE
Unify action interactions for editing in sighting screen

### ISSUE THREAD

**Issue by achou11** [p2panda/meli#82]
Currently noticing 3 different approaches when it comes to performing an action related to editing:

1. **Controls only in card header**: initiating edit mode is done by pressing the header. performing an edit action is done by pressing the header again. In this case there's no explicit "cancel" action.

    e.g. `species_card.dart`

    <img width="300" alt="image" src="https://github.com/p2panda/meli/assets/18542095/1d35d890-2599-4cc4-9acd-46befcda320e">

    <img width="300" alt="image" src="https://github.com/p2panda/meli/assets/18542095/3781eda3-0c61-43b6-acc8-b668b87cbfd9">

2. **Controls only in bottom of card**: initiating edit mode is done by pressing the header. the edit actions are presented as buttons in the bottom during edit mode. 

    e.g. `note_field.dart` 

    <img width="300" alt="image" src="https://github.com/p2panda/meli/assets/18542095/6c973660-bb48-42d4-805e-957c0ef2b32e">

    <img width="300" alt="image" src="https://github.com/p2panda/meli/assets/18542095/29c2f693-4053-4d94-9b4c-615a27de4432">

3. **Controls in both header and bottom of card**: initiating edit mode is done by pressing the header. the edit actions available in both the header and the button at the bottom during edit mode. There is no explicit cancel action.

    e.g. `used_for_field.dart`

    <img width="300" alt="image" src="https://github.com/p2panda/meli/assets/18542095/66fe59d2-f0a0-4821-b5e2-bd9bd58d7297">

    <img width="300" alt="image" src="https://github.com/p2panda/meli/assets/18542095/6bbf7b6c-6e99-4392-ab07-d41302a5c8f6">
    
(1) already existed when I started helping out. I introduced (2) based on what I saw in the mockups. @sandreae introduced (3) via #26 .

Think there should some some unification so the interaction experience is similar for all of these fields. I personally prefer (2) but I think it's more important to be consistent for now 😄  Wondering if there's been previous UX research/feedback to inform us.

**Comment by achou11** [comment]
Oh I'm just noticing that the `Save` button in (3) is actually for saving the value in the `Create New Use` input, not for the whole card. That makes it more similar to (1), but with UI that looks like (2), which is a little confusing and probably should be addressed anyways 😄

**Comment by adzialocha** [comment]
Ah funny, looks related to: https://github.com/p2panda/meli/issues/68

**Comment by sandreae** [comment]
> Oh I'm just noticing that the `Save` button in (3) is actually for saving the value in the `Create New Use` input, not for the whole card. That makes it more similar to (1), but with UI that looks like (2), which is a little confusing and probably should be addressed anyways 😄 

Yes, the Save button here creates a new use and adds it to the sightings uses. The button label is not ideal, it should rather be "Create" or "Create Use" maybe. It definitely didn't feel right or the top level edit toggle button to trigger this behaviour though either.... 

I like option 2 described above in general, but in this case that's also not ideal as you may only want to add some existing tags (not create a new one) in which case you need the edit toggle to exit edit mode when you've finished 🤔

**Comment by adzialocha** [comment]
> > Oh I'm just noticing that the `Save` button in (3) is actually for saving the value in the `Create New Use` input, not for the whole card. That makes it more similar to (1), but with UI that looks like (2), which is a little confusing and probably should be addressed anyways 😄 
> 
> Yes, the Save button here creates a new use and adds it to the sightings uses. The button label is not ideal, it should rather be "Create" or "Create Use" maybe. It definitely didn't feel right or the top level edit toggle button to trigger this behaviour though either.... 
> 
> I like option 2 described above in general, but in this case that's also not ideal as you may only want to add some existing tags (not create a new one) in which case you need the edit toggle to exit edit mode when you've finished 🤔

I understand the suggestion for 2. as a header click only toggling the mode, not doing any action to create / add data. Then it would still work with your pattern?
